---
- name: Ensure python3 is installed
  apt:
    name: python3
    state: present
    update_cache: yes
- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes